### ISSUE TITLE
The program can't handre wrong inputs

### ISSUE THREAD

**Issue by creeloper27** [Chris1101/ArgoMarksGraph#5]
I tryed giving the program some fake credentials and the program crashes immidiatly, i suggest adding a caught for those scenarios, here are my crash errors:

    C:\Users\Cattai_Lorenzo\Desktop\ArgoMarksGraph-master>pyTHON argo-marks-graph.py
    Codice Scuola: 123456
    Username: no
    Password:

    Traceback (most recent call last):
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Program Files\Python36\lib\site-packages\urllib3\util\connection.py", line 60, in                 
    create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Program Files\Python36\lib\socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 11001] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
        chunked=chunked)
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in         
    _make_request
        self._validate_conn(conn)
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in 
    _validate_conn
        conn.connect()
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at     
    0x000002DB7174AE48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 440, in send
        timeout=timeout
      File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Program Files\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.portaleargo.it', port=443): Max         
    retries exceeded with url: /famiglia/api/rest/login (Caused by     
    NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002DB7174AE48>: 
    Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "argo-marks-graph.py", line 110, in <module>
        get_graph()
      File "argo-marks-graph.py", line 6, in get_graph
        avg_all, marks_tot, date_all, marks_dict, time_delta, api_response = 0, 0, [], {},     
    datetime.timedelta(days = 3), get_marks()
      File "argo-marks-graph.py", line 72, in get_marks
        token = json.loads(request('login', loginheader))['token']
      File "argo-marks-graph.py", line 85, in request
    headers = header,
      File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 72, in get
        return request('get', url, params=params, **kwargs)
      File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 58, in request
        return session.request(method=method, url=url, **kwargs)
      File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 508, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.portaleargo.it', port=443):     
    Max retries exceeded with url: /famiglia/api/rest/login (Caused by     
    NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002DB7174AE48>: 
    Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))'

**Comment by creeloper27** [comment]
Still not fixed
